apiVersion: apps/v1
kind: Deployment
metadata:
  name: hm-mgr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: hm-mgr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hm-mgr
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.phpImageVersionName }}:{{ .Values.phpImageVersionTag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              memory: 500Mi
              cpu: 500m
            requests:
              memory: 60Mi
              cpu: 100m
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /Managers/health.php
              port: 80
            periodSeconds: {{ .Values.containers.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: /Managers/health.php
              port: 80
            periodSeconds: {{ .Values.containers.readinessProbe.periodSeconds }}
